### ISSUE TITLE
Membership 2021

### ISSUE THREAD

**Issue by issyl0** [Homebrew/homebrew-governance#18]
Every year around the time of the AGM we ask members from the previous year to confirm they are still interested in being a voting member of Homebrew (and all that that entails - membership of the GitHub org, Slack channels, ability to vote in the AGM).

The 2021 AGM took place last week, so we're asking those who did not vote[1] to confirm that they wish to remain members in 2021/22.

Those members are:

@chenrui333
@dpo
@mxcl
@SeekingMeaning
@suschizu
@tseemann
@woodruffw
@youtux

If you **do** wish to remain a voting member of Homebrew please comment on this issue with 👍🏻, or message me on Slack.

If you **do not** wish to remain a voting member of Homebrew please comment on this issue with 🚀 , or message me on Slack.

Members who have not responded will be removed four weeks from now, that is 2021-03-31.

Thank you!

[1] All votes were anonymous - for those of you not mentioned in this issue who did vote, we do not know who you voted for - we only know who submitted OpaVote ballots as the emailed links were unique to each person.

**Comment by chenrui333** [comment]
👍 

Missed the meeting due to my daily work :(

**Comment by youtux** [comment]
🚀

**Comment by issyl0** [comment]
Reminder that the deadline for "stay" or "go" responses (or none at all) here is tomorrow (Tuesday 30th March). To all of you mentioned here: thank you for all your contributions to Homebrew over the years! ❤️

**Comment by woodruffw** [comment]
:+1: 

Sorry for the extremely belated response; quarantine has not helped my work habits...
