### ISSUE TITLE
Membership 2019

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-governance#2]
If you would like to remain a voting member of the Homebrew organization, please select 👍 and comment below. If you would like to leave the Homebrew organization, please select 🚀 and comment below, or message me privately. Members who have not responded will be removed in three weeks on Monday 2019-04-29.

> 4. The PLC will meet annually to review the status of all members and remove inactive members and those who have not affirmed a commitment to Homebrew in the past year. Voting in the AGM confirms that a member wishes to remain active with the project. After the AGM, the PLC will ask the members who did not vote whether they wish to remain active with the project. The PLC removes any members who don’t respond to this second request after three weeks.

https://docs.brew.sh/Homebrew-Governance#5-meetings-of-the-project-leadership-committee

- [ ] ~@adidalal~
- [x] @alebcay
- [ ] ~@alyssais~
- [x] @amyspark
- [x] @apjanke
- [x] @bfontaine
- [x] @claui
- [x] @colindean
- [x] @dpo
- [x] @EricFromCanada
- [x] @fxcoudert
- [x] @GauthamGoli
- [x] @igas
- [x] @iMichka
- [ ] ~@jacknagel~
- [x] @jacobbednarz
- [x] @jasontedor
- [x] @javian
- [x] @jonchang
- [ ] ~@koraktor~
- [x] @lembacon
- [x] @maxim-belkin
- [x] @MikeMcQuaid
- [x] @mistydemeo
- [x] @Moisan
- [x] @mxcl
- [x] @reitermarkus
- [x] @scpeters
- [x] @Sharpie
- [x] @sjackman
- [x] @SMillerDev
- [ ] ~@tdsmith~
- [x] @tschoonj
- [x] @tseemann
- [x] @victorpopkov
- [x] @vitorgalvao
- [x] @vszakats
- [x] @woodruffw
- [x] @youtux
- [x] @xu-cheng
- [x] @zbeekman
- [x] @zmwangx

**Comment by claui** [comment]
pls tick me

**Comment by tschoonj** [comment]
me too please

**Comment by maxim-belkin** [comment]
I'm a voting member?! 🤑 yay!

**Comment by jasontedor** [comment]
+1

**Comment by colindean** [comment]
:+1: I'm in

**Comment by reitermarkus** [comment]
👍

**Comment by vitorgalvao** [comment]
I’m in.

**Comment by zbeekman** [comment]
For redundancy, 👍

**Comment by amyspark** [comment]
👍

**Comment by dpo** [comment]
Same here!

**Comment by jacobbednarz** [comment]
👍

**Comment by jonchang** [comment]
🙂

**Comment by vszakats** [comment]
\o/

**Comment by scpeters** [comment]
I'm gonna take my horse to the old town road

**Comment by igas** [comment]
I'm in

**Comment by woodruffw** [comment]
Check me please 😄

**Comment by lembacon** [comment]
👍

**Comment by mistydemeo** [comment]
👍

**Comment by Moisan** [comment]
👍

**Comment by SMillerDev** [comment]
But I like rockets :(

**Comment by GauthamGoli** [comment]
👍

**Comment by bfontaine** [comment]
:+1:

**Comment by koraktor** [comment]
🚀 due to current lack of time.

**Comment by victorpopkov** [comment]
:+1: I'm in.

**Comment by adidalal** [comment]
🚀 due to current lack of time. Wishing Homebrew (Cask) all the best!

**Comment by EricFromCanada** [comment]
This is a comment.

**Comment by maxim-belkin** [comment]
This is a response and the beginning of an enlightening conversation.

**Comment by jasontedor** [comment]
This is a tangent that temporarily sidetracks the currently engaging conversation, and I regret having distracted us from the path to englightment that we were on.

**Comment by sjackman** [comment]
Moderator has locked the conversation (off-topic).

**Comment by mxcl** [comment]
I know I'm not much involved anymore, but I think I'd regret being removed, you know?

**Comment by claui** [comment]
@mxcl Hundreds of thousands of services worldwide are running with a `homebrew.mxcl.`… launchd label. Counts as being involved if you ask me.

**Comment by tseemann** [comment]
🚀 COunt me in please @sjackman

**Comment by MikeMcQuaid** [comment]
Paging some previous maintainers @xu-cheng @alyssais @tdsmith @apjanke @adamv @jacknagel who we still see around on some occasion if you're interested in being "members" by the definition of the above document.

**Comment by sjackman** [comment]
Pinging @alebcay @javian @Sharpie @youtux

**Comment by javian** [comment]
Count me in

**Comment by apjanke** [comment]
👍 Yes, please count me in.

**Comment by xu-cheng** [comment]
:+1: for me.

**Comment by tdsmith** [comment]
I decline membership, but thank you for thinking of me!

**Comment by youtux** [comment]
👍, sorry for the late answer.

**Comment by MikeMcQuaid** [comment]
Also paging @chdiza @chrmoritz if you're interested in being voting members without any maintainer obligations.

**Comment by jacknagel** [comment]
I decline, thanks.

**Comment by zmwangx** [comment]
:+1:, thanks.

**Comment by Sharpie** [comment]
I'm in too 👍

**Comment by alyssais** [comment]
No thanks from me, but I appreciate the offer. ❤️

**Comment by alebcay** [comment]
Seeing as this has not been updated in a while, just bumping to say I'm in (liked it a while ago but thought I'd leave a note in case).

**Comment by sjackman** [comment]
Looks like everyone is accounted for. Homebrew has 37 members for 2019.

**Comment by sjackman** [comment]
The only changed needed was to add @zmwangx. Welcome back to Homebrew, Zhiming!

**Comment by zmwangx** [comment]
Thanks!
