### ISSUE TITLE
Repo lacks homepage

### ISSUE THREAD

**Issue by yurikoles** [Homebrew/homebrew-governance#4]

**Comment by MikeMcQuaid** [comment]
@yurikoles You have been repeatedly warned in the past about creating pointless issues and not filling in the issue template. I would block you from the Homebrew organisation indefinitely for this but you do submit useful pull requests. Please only submit pull requests in future and **do not create any more issues in any circumstance**. If you want to ask questions or make statements: do so only Discourse not in issues: https://discourse.brew.sh.

You have been blocked on the Homebrew organisation for a week to stop today's issues. Please adjust your behaviour and focus on your great pull requests in future instead. Sorry and thanks for your contributions.
