### ISSUE TITLE
2020 work in progress

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-governance#7]
- [ ] Determine 2020 membership @sjackman https://github.com/Homebrew/homebrew-governance/issues/9
- [ ] Prepare 2019 financial statements
- [ ] Organize 2020 AGM @MikeMcQuaid

**Comment by issyl0** [comment]
Closing this as we're in 2021 now (and don't wish to be reminded of the 🗑️ 🔥 that was 2020, really).
