### ISSUE TITLE
Membership 2020

### ISSUE THREAD

**Issue by sjackman** [Homebrew/homebrew-governance#9]
If you would like to remain a voting member of the Homebrew organization, please select 👍 and comment below. If you would like to leave the Homebrew organization, please select 🚀 and comment below, or message me privately. Members who have not responded will be removed three weeks after the AGM on Monday 2019-02-24.

> 4. The PLC will meet annually to review the status of all members and remove inactive members and those who have not affirmed a commitment to Homebrew in the past year. Voting in the AGM confirms that a member wishes to remain active with the project. After the AGM, the PLC will ask the members who did not vote whether they wish to remain active with the project. The PLC removes any members who don’t respond to this second request after three weeks.

https://docs.brew.sh/Homebrew-Governance#5-meetings-of-the-project-leadership-committee

- [x] @alebcay
- [ ] @amyspark
- ~~@apjanke~~
- [x] @bfontaine
- [x] @chenrui333
- [x] @claui
- [x] @colindean
- [x] @dawidd6
- [x] @dpo
- [x] @EricFromCanada
- [x] @fxcoudert
- [x] @GauthamGoli
- [x] @igas
- [x] @iMichka
- [x] @issyl0
- [x] @jacobbednarz
- ~~@jasontedor~~
- [ ] @javian
- [x] @jonchang
- ~~@ladislas~~
- [x] @lembacon
- [x] @maxim-belkin
- [x] @MikeMcQuaid
- [x] @mistydemeo
- [x] @Moisan
- [x] @mxcl
- [x] @reitermarkus
- [x] @scpeters
- ~~@Sharpie~~
- [x] @sjackman
- [x] @SMillerDev
- [x] @tschoonj
- [x] @tseemann
- [x] @victorpopkov
- [x] @vitorgalvao
- [x] @vszakats
- [x] @woodruffw
- [x] @xu-cheng
- [x] @youtux
- [x] @zachauten
- [x] @zbeekman
- [x] @zmwangx

**Comment by SMillerDev** [comment]
I vote remain?

**Comment by sjackman** [comment]
Too soon, Sean. 😆🤦‍♂️

**Comment by jonchang** [comment]
👍

**Comment by victorpopkov** [comment]
:+1:

**Comment by tschoonj** [comment]
👍

**Comment by GauthamGoli** [comment]
👍

**Comment by fxcoudert** [comment]
To Infinity and Beyond!

**Comment by iMichka** [comment]
👍

**Comment by scpeters** [comment]
I never got laser eye surgery but somehow I reached 2020

**Comment by dawidd6** [comment]
:+1:

**Comment by reitermarkus** [comment]
👍

**Comment by claui** [comment]
👍

**Comment by jacobbednarz** [comment]
👍

**Comment by EricFromCanada** [comment]
👍

**Comment by xu-cheng** [comment]
👍

**Comment by apjanke** [comment]
🚀 I'm still a Homebrew fan, but I don't have enough time to keep up with the project this year. Cheers!

**Comment by mxcl** [comment]
👍 cheers.

**Comment by chenrui333** [comment]
👍

**Comment by youtux** [comment]
👍

**Comment by maxim-belkin** [comment]
👍

**Comment by zbeekman** [comment]
👍

**Comment by igas** [comment]
👍

**Comment by vszakats** [comment]
👍

**Comment by vitorgalvao** [comment]
👍

**Comment by zachauten** [comment]
👍

**Comment by colindean** [comment]
:thumbsup:

**Comment by bfontaine** [comment]
🚀 I’m ok with maintaining [`homebrew-command-not-found`](https://github.com/Homebrew/homebrew-command-not-found) but I’ve not been involved in the rest of the project so it makes no sense to stay a voting member of the org. Does leaving the PLC means leaving the Homebrew org on GitHub? If so I won’t be able to maintain hcnf anymore.

**Comment by woodruffw** [comment]
:+1:

**Comment by reitermarkus** [comment]
@bfontaine, being a voting member is essentially equivalent to being an org member. If you continue maintaining `homebrew-command-not-found` it definitely makes sense for you to continue being a voting member.

**Comment by bfontaine** [comment]
Ok, thanks @reitermarkus, so I’m staying :+1:

**Comment by zmwangx** [comment]
👍

**Comment by lembacon** [comment]
👍

**Comment by Moisan** [comment]
👍

**Comment by mistydemeo** [comment]
👍🏻

**Comment by dpo** [comment]
👍

**Comment by Sharpie** [comment]
🚀 These days I'm primarily a Homebrew user. The amount of attention I've been able to give to the project over the past year is too low to justify remaining as a voting member.

Y'all are doing fantastic work, keep it up!

**Comment by tseemann** [comment]
👍 #nohomeBREwXIT

**Comment by alebcay** [comment]
hello yes i am alive and vote remain 👍

**Comment by sjackman** [comment]
@amyspark @jasontedor @javian @ladislas Would you like to remain a member of Homebrew?

**Comment by jasontedor** [comment]
While I cherish Homebrew as a piece of software that I use regularly, I regret that I simply do not have the attention and time to justify remaining as a maintainer. I am thankful that I had the opportunity to be a maintainer. Thank you to you and all the other continuing maintainers for keeping Homebrew going!

**Comment by ladislas** [comment]
🚀 same as the others, homebrew and brew test bot are amazing pieces of software and tools that I use on a daily basis but unfortunately I don't have enough time on my hands to be a full member. I'm keeping a close look at everything that is happening :)
